# Generated by Django 6.0.1 on 2026-01-07 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_id', models.CharField(max_length=64, unique=True)),
                ('cohort', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('self_report_ai_use', models.IntegerField(choices=[(-1, 'Unknown'), (0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Full / Heavy use')], default=-1)),
                ('ai_disclosure_text', models.TextField(blank=True)),
                ('prompt_used', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submissions.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assignment', 'created_at'], name='submissions_assignm_5f3624_idx'), models.Index(fields=['student'], name='submissions_student_b34bff_idx')],
            },
        ),
    ]
