# Generated by Django 6.0.1 on 2026-01-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('term', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', 'name'],
                'unique_together': {('name', 'term', 'institution')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prompt_text', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('requires_sources', models.BooleanField(default=False)),
                ('min_words', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
            options={
                'ordering': ['-created_at', 'course__name', 'title'],
                'unique_together': {('course', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_allowed', models.CharField(choices=[('NOT_ALLOWED', 'Not allowed'), ('ASSIST_ALLOWED', 'Assist allowed (editing, brainstorming)'), ('FULL_ALLOWED', 'Full allowed (generation permitted)')], default='ASSIST_ALLOWED', max_length=20)),
                ('ai_disclosure_required', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='courses.assignment')),
            ],
        ),
    ]
