# Generated by Django 6.0.1 on 2026-01-07 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='courses.assignment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CLASSIFIER', 'Classifier'), ('REGRESSOR', 'Regressor'), ('CLUSTERING', 'Clustering'), ('VISUALIZATION', 'Visualization'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='analysis.analysisrun')),
            ],
            options={
                'ordering': ['analysis_run', 'type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(blank=True, default=dict)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('ai_similarity', models.FloatField(blank=True, null=True)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('predicted_ai_assist_prob', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_features', to='analysis.analysisrun')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='submissions.submission')),
            ],
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['assignment', 'created_at'], name='analysis_an_assignm_78419c_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionfeatures',
            index=models.Index(fields=['analysis_run'], name='analysis_su_analysi_3559e6_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionfeatures',
            index=models.Index(fields=['cluster_id'], name='analysis_su_cluster_067246_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionfeatures',
            unique_together={('analysis_run', 'submission')},
        ),
    ]
