# Generated by Django 6.0.1 on 2026-01-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_id', models.IntegerField()),
                ('submission_id', models.UUIDField()),
                ('student_anon_id', models.CharField(max_length=64)),
                ('umap_x', models.FloatField()),
                ('umap_y', models.FloatField()),
                ('cluster', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisrun')),
            ],
        ),
    ]
