# Generated by Django 6.0.1 on 2026-01-07 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_clusteringresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_id', models.IntegerField()),
                ('cluster', models.IntegerField()),
                ('label', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisrun')),
            ],
            options={
                'unique_together': {('analysis_run', 'rubric_id', 'cluster')},
            },
        ),
    ]
