# Generated by Django 6.0.1 on 2026-01-07 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='courses.assignment')),
            ],
            options={
                'ordering': ['assignment__course__name', 'assignment__title', 'name'],
                'unique_together': {('assignment', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.PositiveIntegerField(default=4)),
                ('weight', models.FloatField(default=1.0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='rubrics.rubric')),
            ],
            options={
                'ordering': ['rubric', 'order', 'id'],
                'unique_together': {('rubric', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RubricScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='rubrics.rubriccriterion')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_scores', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_scores', to='submissions.submission')),
            ],
            options={
                'indexes': [models.Index(fields=['submission'], name='rubrics_rub_submiss_cf7ebc_idx'), models.Index(fields=['criterion'], name='rubrics_rub_criteri_8d14ec_idx'), models.Index(fields=['rater'], name='rubrics_rub_rater_i_ad2231_idx')],
                'unique_together': {('submission', 'criterion', 'rater')},
            },
        ),
    ]
