# Generated by Django 6.0.1 on 2026-01-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriccriterion',
            name='is_depth',
            field=models.BooleanField(default=False),
        ),
    ]
